version: '3.2'
services:
  gogs:
    image: gogs/gogs
    container_name: gogs
    restart: always
    volumes:
      - gogs_data:/data
    ports:
      - "10022:22"
      - "10080:3000"

volumes:
  gogs_data:


